### ISSUE TITLE
skipping beta message

### ISSUE THREAD

**Issue by a-dekker** [ricbit/aleste2#1]
Great job on converting this to rom!
But as I am used to play without keyboard (custom raspberry pi console emulation here), I can't skip the beta message without hooking up a keyboard.
Could you make the message timeout after a few seconds, or make it accept joystick input?

**Comment by ricbit** [comment]
Sure thing, great suggestion.

**Comment by ricbit** [comment]
This is now fixed, please check the new binary:

[http://www.ricbit.com/temp/aleste2.zip](http://www.ricbit.com/temp/aleste2.zip)

**Comment by a-dekker** [comment]
Hmm, I encounter some problems now. It works fine in openmsx, but in (lr-)bluemsx (which I mostly use for games) it shows a dump of charactersets at start and after pressing the joystick button it ends up in a flickering blue/darkblue screen.

**Comment by ricbit** [comment]
Thanks for the report, I'll look into this issue tonight.
